prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'gemini-server'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: gemini-server